-- Review as DBA in the intended PDB/container, after creating ASH_READER.
-- No passwords, account creation, broad roles, or write privileges.
GRANT CREATE SESSION TO ASH_READER;
GRANT SELECT ON SYS.V_$DATABASE TO ASH_READER;
GRANT SELECT ON SYS.V_$INSTANCE TO ASH_READER;
GRANT SELECT ON SYS.V_$PARAMETER TO ASH_READER;
GRANT SELECT ON SYS.DBA_USERS TO ASH_READER;
GRANT SELECT ON SYS.V_$SQL TO ASH_READER;
GRANT SELECT ON SYS.V_$SQL_PLAN TO ASH_READER;
